# Generated by Django 5.2.8 on 2025-12-03 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
        ('grades', '0001_initial'),
        ('students', '0005_rename_grade_level_student_class_level'),
        ('teachers', '0004_alter_subject_options_remove_teacher_subjects_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('MIDTERM', 'Midterm Test'), ('ASSIGNMENT1', 'Assignment 1'), ('ASSIGNMENT2', 'Assignment 2'), ('EXAM', 'Final Exam')], max_length=20)),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('class_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_entries', to='classes.classsubject')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='students.student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades_entered', to='teachers.teacher')),
            ],
            options={
                'unique_together': {('student', 'class_subject', 'category')},
            },
        ),
        migrations.DeleteModel(
            name='Grade',
        ),
    ]
