# Generated by Django 5.2.11 on 2026-03-02 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0002_initial'),
        ('grades', '0002_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradeentry',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades_entered', to='teachers.teacher'),
        ),
        migrations.AddField(
            model_name='gradeentry',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_entries', to='classes.term'),
        ),
        migrations.AlterUniqueTogether(
            name='gradeentry',
            unique_together={('student', 'class_subject', 'term', 'category')},
        ),
    ]
