# Generated by Django 5.2.7 on 2025-11-24 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_alter_student_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='grade_level',
            new_name='class_level',
        ),
    ]
