# Generated by Django 5.2.11 on 2026-03-02 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0002_initial'),
        ('schools', '__first__'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classsubject',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_subjects', to='teachers.teacher'),
        ),
        migrations.AddField(
            model_name='classsubjectpermission',
            name='class_subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='classes.classsubject'),
        ),
        migrations.AddField(
            model_name='classsubjectpermission',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_permissions', to='teachers.teacher'),
        ),
        migrations.AddField(
            model_name='schoolclass',
            name='class_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes_managed', to='teachers.teacher'),
        ),
        migrations.AddField(
            model_name='schoolclass',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.school'),
        ),
        migrations.AddField(
            model_name='classsubject',
            name='school_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='classes.schoolclass'),
        ),
        migrations.AddField(
            model_name='term',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='classes.academicsession'),
        ),
        migrations.AlterUniqueTogether(
            name='academicsession',
            unique_together={('school', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='classsubjectpermission',
            unique_together={('class_subject', 'teacher')},
        ),
        migrations.AlterUniqueTogether(
            name='classsubject',
            unique_together={('school_class', 'subject')},
        ),
        migrations.AlterUniqueTogether(
            name='term',
            unique_together={('session', 'name')},
        ),
    ]
