# Generated by Django 5.2.7 on 2025-11-15 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parent',
            name='email',
        ),
        migrations.AlterField(
            model_name='parent',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
